const express=require('express');const multer=require('multer');const path=require('path');const fs=require('fs');
const app=express();const PORT=process.env.PORT||3000;const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'13279712';
const PUBLIC=path.join(__dirname,'public'),DATA=path.join(__dirname,'data'),VIDEOS=path.join(PUBLIC,'videos'),DB=path.join(DATA,'videos.json');
fs.mkdirSync(VIDEOS,{recursive:true});if(!fs.existsSync(DB))fs.writeFileSync(DB,'[]','utf8');app.use(express.json({limit:'1mb'}));app.use(express.static(PUBLIC));
function read(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{return []}}function save(x){fs.writeFileSync(DB,JSON.stringify(x,null,2),'utf8')}function admin(req){return req.headers['x-admin-password']===ADMIN_PASSWORD||req.body?.password===ADMIN_PASSWORD}
const storage=multer.diskStorage({destination:(_r,_f,cb)=>cb(null,VIDEOS),filename:(_r,f,cb)=>cb(null,Date.now()+'-'+Math.random().toString(36).slice(2,9)+path.extname(f.originalname).toLowerCase())});
const upload=multer({storage,limits:{fileSize:250*1024*1024},fileFilter:(_r,f,cb)=>cb(null,!!f.mimetype?.startsWith('video/'))});
app.post('/api/login',(req,res)=>res.json({ok:req.body?.password===ADMIN_PASSWORD}));app.get('/api/videos',(_r,res)=>res.json(read()));
app.post('/api/videos',(req,res)=>upload.single('video')(req,res,err=>{if(err)return res.status(400).json({error:err.message});if(!admin(req)){if(req.file)fs.rmSync(req.file.path,{force:true});return res.status(401).json({error:'Senha incorreta.'})}if(!req.file)return res.status(400).json({error:'Selecione um vídeo.'});const item={id:Date.now().toString(),title:String(req.body.title||'Vídeo de Sensi').slice(0,120),brand:String(req.body.brand||'Geral'),level:String(req.body.level||'Média'),description:String(req.body.description||'').slice(0,500),url:'/videos/'+req.file.filename};const a=read();a.unshift(item);save(a);res.json({ok:true,item})}));
app.delete('/api/videos/:id',(req,res)=>{if(!admin(req))return res.status(401).json({error:'Senha incorreta.'});const a=read(),v=a.find(x=>x.id===req.params.id);if(!v)return res.status(404).json({error:'Vídeo não encontrado.'});fs.rmSync(path.join(PUBLIC,v.url.replace(/^\/+/,'')),{force:true});save(a.filter(x=>x.id!==req.params.id));res.json({ok:true})});
app.get('*',(_r,res)=>res.sendFile(path.join(PUBLIC,'index.html')));app.listen(PORT,'0.0.0.0',()=>console.log('Demenor Sensi rodando na porta '+PORT));
